# Generated by Django 5.0.4 on 2024-04-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_alter_post_options_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(verbose_name='Дата воспоминания'),
        ),
    ]
