# Generated by Django 5.0.4 on 2024-04-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_alter_memory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='place_name',
            field=models.CharField(default=0, max_length=150, verbose_name='Название места воспоминания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='coordinates',
            field=models.CharField(max_length=150, verbose_name='Место воспоминания'),
        ),
    ]
